version: "2"

run:
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  timeout: 5m

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
    - goconst
    - unconvert
    - unparam
    - gocyclo
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - unparam
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/v2/pkg/logutils.Log).Fatalf
    staticcheck:
      checks:
        - all

formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    warn-unused: false
    generated: lax
  settings:
    gofmt:
      simplify: true

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
