run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Essential linters
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Code quality
    - gofmt
    - goimports
    - goconst
    - misspell
    - unconvert
    - unparam

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam

  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
